version: "3.3"

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    restart: always
    networks:
      - frontend
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./traefik.yml:/traefik.yml"
      - "./config.yml:/config.yml"
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    # labels:
    #   - "traefik.enable=true"

  # portainer:
  #   image: portainer/portainer-ce
  #   container_name: portainer-tf
  #   restart: always
  #   networks:
  #     - frontend
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - portainer_data:/data
  #   labels:
  #     - traefik.enable=true

networks:
  frontend:
    external: true
