version: "3"

services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: dns-server
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    environment:
      - TZ=Asia/Shanghai
      - BIND9_USER=root
