services:
  ollama:
    container_name: ollama
    image: ollama/ollama:0.4.2
    restart: always
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    # models to download: ollama pull nomic-embed-text llama3.2 phi3.5

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    restart: always
    ports:
      - "6333:6333" #http://127.0.0.1:6333/dashboard
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant_storage/qdrant/storage:z

  openwebui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:0.3.16
    restart: always
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - "OPENAI_API_BASE_URLS=${OPENAI_API_BASE_URLS}"
      - "OPENAI_API_KEYS=${OPENAI_API_KEYS}"

volumes:
  open-webui:
  qdrant-data:
  ollama:
# networks:
#   database-net:
#     name: database_network
#     external: true
