services:
  # chromadb:
  #   container_name: chromadb
  #   image: chromadb/chroma
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - chroma-data:/chroma/chroma

  # vector-admin:
  #   container_name: vector-admin
  #   image: mintplexlabs/vectoradmin
  #   restart: always
  #   ports:
  #     - "3001:3001"
  #     - "3355:3355"
  #     - "8288:8288"
  #   environment:
  #     - SERVER_PORT=3001
  #     - JWT_SECRET=25cbbab2-97d3-4e85-bd75-b2c927a8bd5f
  #     - INNGEST_EVENT_KEY=background_workers
  #     - INNGEST_SIGNING_KEY=25cbbab2-97d3-4e85-bd75-b2c927a8bd5f
  #     - INNGEST_LANDING_PAGE=true
  #     - DATABASE_CONNECTION_STRING=postgresql://appuser:adminPassword@host.docker.internal:5432/vdbms
  #   depends_on:
  #     - chromadb
  #   volumes:
  #     - vectoradmin-data:/app/backend/storage
  #   networks:
  #     - database-net

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    restart: always
    ports:
      - "6333:6333" #http://127.0.0.1:6333/dashboard
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant_storage/qdrant/storage:z

  openwebui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:0.3.16
    restart: always
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - "OPENAI_API_BASE_URLS=${OPENAI_API_BASE_URLS}"
      - "OPENAI_API_KEYS=${OPENAI_API_KEYS}"

volumes:
  open-webui:
  qdrant-data:
  # vectoradmin-data:
  # chroma-data:
# networks:
#   database-net:
#     name: database_network
#     external: true
