receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
            allowed_origins:
              - "http://*"
              - "https://*"
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:
 
exporters:  
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
      
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

  prometheus:
    endpoint: "otelcol:9464"
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true

  logging:
    verbosity: detailed

processors:
  batch:
  filter:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - queueSize

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

connectors:
  spanmetrics:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, logging, spanmetrics, jaeger]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [filter, batch]
      exporters: [prometheus, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]