global:
  scrape_interval:     10s
  evaluation_interval: 30s
  external_labels:
    cluster: docker-compose
    namespace: docker-compose

rule_files:
  - /etc/prometheus/rules.yaml
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: otel-collector-job  
    honor_labels: true
    static_configs:
    - targets: ["otelcol:9201"]

  # - job_name: traefik-job
  #   metrics_path: /v1/metrics
  #   static_configs:
  #     - targets: ["host.docker.internal:8082"]
      
  - job_name: minio-job
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: [ "minio:9000" ]

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080', 'node-exporter:9100']

  - job_name: 'rabbitmq-server'
    static_configs:
      - targets:
          - 'host.docker.internal:15692'
 
  - job_name: churchportal-api
    static_configs:
    - targets: ['host.docker.internal:5161']  
      