version: "3.3"

services:
  postgres-server:
    image: postgres:15.3-alpine
    container_name: postgres-server
    restart: always
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=Ideas@Devs2024
      - POSTGRES_DB=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C --locale-provider=icu --icu-locale=C --locale=en_US.UTF-8
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data   
    deploy:
      resources:
        limits:
          memory: 1G

  portainer:
    image: portainer/portainer-ce:2.19.4
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    deploy:
      resources:
        limits:
          memory: 150M

volumes:
  portainer_data:
  pgdata:

