version: '3.7'

services:
  # mariadb-server:
  #   image: mariadb
  #   container_name: Mariadb-Server
  #   # command: --default-authentication-plugin=mysql_native_password
  #   restart: on-failure
  #   command: --lower_case_table_names=2
  #   environment: 
  #     - MYSQL_USER=appuser
  #     - MYSQL_PASSWORD=P@ssword1
  #     - MYSQL_ROOT_PASSWORD=P@ssword1
  #     # - MYSQL_DATABASE=DockerTest-Dev    
  #   ports:
  #     - 3306:3306
  #   volumes:
  #   - mariadb:/var/lib/mysql
#
#  mssql-server:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    container_name: mssql-server
#    restart: on-failure
#    environment: 
#      - ACCEPT_EULA=Y
#      - MSSQL_SA_PASSWORD=adminPassword
#      - MSSQL_PID=Express       
#    ports: 
#      - 1433:1433  
#    volumes:
#      - mssql-data:/var/opt/mssql
#
  # mysql-server:
  #   image: library/mysql:8.0.23
  #   container_name: MySQL-Server
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: on-failure
  #   environment: 
  #     - MYSQL_RANDOM_ROOT_PASSWORD=1
  #     - MYSQL_USER=appuser
  #     - MYSQL_PASSWORD=Password1
  #     - MYSQL_ROOT_PASSWORD=Password1
  #   ports:
  #     - 3307:3306
  #   volumes:
  #     - mysqldata:/var/lib/mysql
  #     - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d

  postgres-server:
    image: postgres
    container_name: postgres-server
    restart: always
    environment: 
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=adminPassword
      - POSTGRES_DB=postgres
    ports: 
      - 5432:5432    
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb-server:
   image: mongo:6.0.3
   container_name: mongo-server
   restart: always
   environment: 
     - MONGO_INITDB_ROOT_USERNAME=appuser
     - MONGO_INITDB_ROOT_PASSWORD=adminPassword
   ports: 
     - 27017:27017    
   volumes:
     - mongo-data:/data/db

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express-app
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=appuser
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=adminPassword
  #     # - ME_CONFIG_MONGODB_URL=mongodb://appuser:adminPassword@mongodb-server:27017/
  #     - ME_CONFIG_MONGODB_SERVER=mongodb-server
  
  redis-server:
    image: redis
    container_name: redis-server
    restart: always
    ports: 
      - 6379:6379    
    volumes:
      - redis-data:/data

volumes:
#  mssql-data:
  pgdata:
  mongo-data:
  redis-data:
