version: '3.8'

services:
  reverse-proxy-server:
    image: jc21/nginx-proxy-manager:latest
    container_name: Reverse-Proxy-Server
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt


  # adminer:
  #   container_name: adminer-test
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 9090:8080
