version: '3.8'

services:
  # reverse-proxy-server:
  #   image: jc21/nginx-proxy-manager:latest
  #   container_name: Reverse-Proxy-Server
  #   restart: always
  #   ports:
  #     - '80:80'
  #     - '81:81'
  #     - '443:443'
  #   volumes:
  #     - ./data:/data
  #     - ./letsencrypt:/etc/letsencrypt

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: always
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=user@mail.com
  #     - PGADMIN_DEFAULT_PASSWORD=P@ssword1
  #   ports:
  #     - "5050:80"
  #   volumes:
  #     - pgadmin_data:/root/.pgadmin
 
  rabbitmq:
    image: rabbitmq:3.11.11-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq-server
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=appuser
      - RABBITMQ_DEFAULT_PASS=adminPassword

  # portainer:
  #   image: portainer/portainer-ce:latest
  #   container_name: portainer
  #   restart: always
  #   ports:
  #     - "9000:9000"
  #     - "9443:9443"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data

volumes:
  # pgadmin_data:
  portainer_data: